In [2]:
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt

In [3]:
good_reads = pd.read_csv('./goodreads_books.csv')
good_reads.head()

,id,title,link,series,cover_link,author,author_link,rating_count,review_count,average_rating,...,isbn13,asin,settings,characters,awards,amazon_redirect_link,worldcat_redirect_link,recommended_books,books_in_series,description
0,630104,Inner Circle,https://www.goodreads.com//book/show/630104.In...,(Private #5),https://i.gr-assets.com/images/S/compressed.ph...,"Kate Brian, Julian Peploe",https://www.goodreads.com/author/show/94091.Ka...,7597,196,4.03,...,9781416950417,NaN,NaN,NaN,NaN,https://www.goodreads.com//book_link/follow/17...,https://www.goodreads.com//book_link/follow/8?...,"726458, 726458, 1537534, 3047848, 1651302, 304...","381489, 381501, 352428, 630103, 1783281, 17832...",Reed Brennan arrived at Easton Academy expecti...
1,9487,A Time to Embrace,https://www.goodreads.com//book/show/9487.A_Ti...,(Timeless Love #2),https://i.gr-assets.com/images/S/compressed.ph...,Karen Kingsbury,https://www.goodreads.com/author/show/3159984....,4179,177,4.35,...,9781595542328,NaN,NaN,NaN,NaN,https://www.goodreads.com//book_link/follow/17...,https://www.goodreads.com//book_link/follow/8?...,"127352, 127352, 40642197, 127353, 127354, 3891...",115036,"Ideje az Ã¶lelÃ©snek TÃ¶rtÃ©net a remÃ©nyrÅl,..."
2,6050894,Take Two,https://www.goodreads.com//book/show/6050894-t...,(Above the Line #2),https://i.gr-assets.com/images/S/compressed.ph...,Karen Kingsbury,https://www.goodreads.com/author/show/3159984....,6288,218,4.23,...,NaN,NaN,"Bloomington, Indiana(United States)",NaN,NaN,https://www.goodreads.com//book_link/follow/17...,https://www.goodreads.com//book_link/follow/8?...,"706250, 706250, 666481, 11942636, 706241, 1273...","4010795, 40792877, 7306261",Filmmakers Chase Ryan and Keith Ellison have c...
3,39030,Reliquary,https://www.goodreads.com//book/show/39030.Rel...,(Pendergast #2),https://i.gr-assets.com/images/S/compressed.ph...,"Douglas Preston, Lincoln Child",https://www.goodreads.com/author/show/12577.Do...,38382,1424,4.01,...,9780765354952,NaN,"New York State(United States) New York City, N...","Aloysius X.L. Pendergast, Margo Green, William...",NaN,https://www.goodreads.com//book_link/follow/17...,https://www.goodreads.com//book_link/follow/8?...,"39026, 39026, 11007668, 3986318, 51887330, 194...","67035, 39031, 39033, 136637, 136638, 30068, 39...",NaN
4,998,The Millionaire Next Door: The Surprising Secr...,https://www.goodreads.com//book/show/998.The_M...,NaN,https://i.gr-assets.com/images/S/compressed.ph...,"Thomas J. Stanley, William D. Danko",https://www.goodreads.com/author/show/659.Thom...,72168,3217,4.04,...,9780671015206,NaN,NaN,NaN,Independent Publisher Book Award (IPPY) Nomine...,https://www.goodreads.com//book_link/follow/17...,https://www.goodreads.com//book_link/follow/8?...,"1052, 1052, 763362, 69571, 78427, 30186948, 10...",NaN,The incredible national bestseller that is cha...

In [4]:
good_reads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52199 entries, 0 to 52198
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      52199 non-null  int64
 1   title                   52199 non-null  object
 2   link                    52199 non-null  object
 3   series                  23319 non-null  object
 4   cover_link              51592 non-null  object
 5   author                  52199 non-null  object
 6   author_link             52199 non-null  object
 7   rating_count            52199 non-null  int64
 8   review_count            52199 non-null  int64
 9   average_rating          52199 non-null  float64
 10  five_star_ratings       52199 non-null  int64
 11  four_star_ratings       52199 non-null  int64
 12  three_star_ratings      52199 non-null  int64
 13  two_star_ratings        52199 non-null  int64
 14  one_star_ratings        52199 non-null  int64
 15  number_of_pages         49869 non-null  float64
 16  date_published          51339 non-null  object
 17  publisher               48563 non-null  object
 18  original_title          39250 non-null  object
 19  genre_and_votes         49359 non-null  object
 20  isbn                    40316 non-null  object
 21  isbn13                  39507 non-null  object
 22  asin                    5236 non-null   object
 23  settings                11515 non-null  object
 24  characters              13695 non-null  object
 25  awards                  10626 non-null  object
 26  amazon_redirect_link    52199 non-null  object
 27  worldcat_redirect_link  48214 non-null  object
 28  recommended_books       48205 non-null  object
 29  books_in_series         22078 non-null  object
 30  description             49624 non-null  object
dtypes: float64(2), int64(8), object(21)
memory usage: 12.3+ MB

### Dropping unwanted columns

In [5]:
good_reads.drop(columns = ['id', 'link', 'cover_link', 'author_link', 'date_published', 'original_title', 'asin', 'settings',
                'characters', 'amazon_redirect_link', 'worldcat_redirect_link', 'recommended_books', 'books_in_series',
                'isbn', 'isbn13'], axis = 1,
               inplace=True)

In [6]:
#good_reads['is_series'] = good_reads.series.notnull().astype('int')
#good_reads['has_won_award'] = good_reads.awards.notnull().astype('int')
#initialize target column
good_reads['nyt_best_seller'] = np.zeros(len(good_reads)).astype(int)
#good_reads.drop(columns=['series', 'awards'], axis = 1, inplace = True)
good_reads.head()

,title,series,author,rating_count,review_count,average_rating,five_star_ratings,four_star_ratings,three_star_ratings,two_star_ratings,one_star_ratings,number_of_pages,publisher,genre_and_votes,awards,description,nyt_best_seller
0,Inner Circle,(Private #5),"Kate Brian, Julian Peploe",7597,196,4.03,3045,2323,1748,389,92,220.0,Simon Schuster Books for Young Readers,"Young Adult 161, Mystery 45, Romance 32",NaN,Reed Brennan arrived at Easton Academy expecti...,0
1,A Time to Embrace,(Timeless Love #2),Karen Kingsbury,4179,177,4.35,2255,1290,518,93,23,400.0,Thomas Nelson,"Christian Fiction 114, Christian 45, Fiction 3...",NaN,"Ideje az Ã¶lelÃ©snek TÃ¶rtÃ©net a remÃ©nyrÅl,...",0
2,Take Two,(Above the Line #2),Karen Kingsbury,6288,218,4.23,3000,2020,1041,183,44,320.0,Zondervan,"Christian Fiction 174, Christian 81, Fiction 58",NaN,Filmmakers Chase Ryan and Keith Ellison have c...,0
3,Reliquary,(Pendergast #2),"Douglas Preston, Lincoln Child",38382,1424,4.01,12711,15407,8511,1429,324,464.0,Tor Books,"Thriller 626, Mystery 493, Horror 432, Fiction...",NaN,NaN,0
4,The Millionaire Next Door: The Surprising Secr...,NaN,"Thomas J. Stanley, William D. Danko",72168,3217,4.04,27594,25219,14855,3414,1086,258.0,Gallery Books,"Economics-Finance 1162, Nonfiction 910, Busine...",Independent Publisher Book Award (IPPY) Nomine...,The incredible national bestseller that is cha...,0

### Dropping Missing Values and Duplicates

In [ ]:
good_reads = good_reads.dropna(axis=0, subset=['publisher', 'genre_and_votes', 'description']).reset_index()
good_reads.isnull().sum().sort_values(ascending=False)

In [8]:
good_reads['number_of_pages'].fillna(good_reads['number_of_pages'].mean(), inplace=True)

In [9]:
good_reads.drop_duplicates(subset='title', keep='first', inplace=True)
good_reads.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42340 entries, 0 to 44366
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               42340 non-null  int64
 1   title               42340 non-null  object
 2   series              19293 non-null  object
 3   author              42340 non-null  object
 4   rating_count        42340 non-null  int64
 5   review_count        42340 non-null  int64
 6   average_rating      42340 non-null  float64
 7   five_star_ratings   42340 non-null  int64
 8   four_star_ratings   42340 non-null  int64
 9   three_star_ratings  42340 non-null  int64
 10  two_star_ratings    42340 non-null  int64
 11  one_star_ratings    42340 non-null  int64
 12  number_of_pages     42340 non-null  float64
 13  publisher           42340 non-null  object
 14  genre_and_votes     42340 non-null  object
 15  awards              9676 non-null   object
 16  description         42340 non-null  object
 17  nyt_best_seller     42340 non-null  int64
dtypes: float64(2), int64(9), object(7)
memory usage: 6.1+ MB

In [10]:
nyt = pd.read_pickle('full_nyt.pkl')
nyt.drop_duplicates('title', keep='first', inplace=True)
nyt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21167 entries, 0 to 21166
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             21167 non-null  object
 1   description       11472 non-null  object
 2   contributor       11485 non-null  object
 3   author            21167 non-null  object
 4   contributor_note  11484 non-null  object
 5   price             21167 non-null  float64
 6   age_group         11484 non-null  object
 7   publisher         11485 non-null  object
 8   isbns             21167 non-null  object
 9   ranks_history     21167 non-null  object
 10  reviews           21167 non-null  object
dtypes: float64(1), object(10)
memory usage: 1.9+ MB

In [11]:
nyt2 = pd.read_json('./nyt2.json', lines=True)
nyt2.drop(columns=['_id', 'bestsellers_date', 'published_date', 'amazon_product_url',
                   'price', 'rank', 'rank_last_week', 'weeks_on_list'], inplace=True)
nyt2.drop_duplicates(subset='title', keep='first', inplace=True)
nyt2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2300 entries, 0 to 10194
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   author       2300 non-null   object
 1   description  2300 non-null   object
 2   publisher    2300 non-null   object
 3   title        2300 non-null   object
dtypes: object(4)
memory usage: 89.8+ KB

In [12]:
good_reads['title'] = [title.lower() for title in good_reads.title.tolist()]
nyt['title'] = [title.lower() for title in nyt.title.tolist()]
nyt2['title'] = [title.lower() for title in nyt2.title.tolist()]

In [13]:
matched = 0
nyt_notin_gr = 0 
for title in nyt2.title.tolist():
    if title in good_reads.title.tolist():
        good_reads.loc[good_reads.title == title, 'nyt_best_seller'] = 1
        matched += 1
    else:
        nyt_notin_gr += 1

In [14]:
good_reads.nyt_best_seller.value_counts()

0    41286
1     1054
Name: nyt_best_seller, dtype: int64

In [15]:
matched = []
matched_num = 0
for title in nyt.title.tolist():
    if title in good_reads.title.tolist():
        good_reads.loc[good_reads.title == title, 'nyt_best_seller'] = 1
        matched_num+=1
    else:
        pass

In [16]:
matched_num

3328

In [17]:
good_reads.nyt_best_seller.value_counts()

0    38699
1     3641
Name: nyt_best_seller, dtype: int64

In [18]:
good_reads.drop(columns='index', axis=1, inplace=True)

In [19]:
good_reads

,title,series,author,rating_count,review_count,average_rating,five_star_ratings,four_star_ratings,three_star_ratings,two_star_ratings,one_star_ratings,number_of_pages,publisher,genre_and_votes,awards,description,nyt_best_seller
0,inner circle,(Private #5),"Kate Brian, Julian Peploe",7597,196,4.03,3045,2323,1748,389,92,220.0,Simon Schuster Books for Young Readers,"Young Adult 161, Mystery 45, Romance 32",NaN,Reed Brennan arrived at Easton Academy expecti...,0
1,a time to embrace,(Timeless Love #2),Karen Kingsbury,4179,177,4.35,2255,1290,518,93,23,400.0,Thomas Nelson,"Christian Fiction 114, Christian 45, Fiction 3...",NaN,"Ideje az Ã¶lelÃ©snek TÃ¶rtÃ©net a remÃ©nyrÅl,...",0
2,take two,(Above the Line #2),Karen Kingsbury,6288,218,4.23,3000,2020,1041,183,44,320.0,Zondervan,"Christian Fiction 174, Christian 81, Fiction 58",NaN,Filmmakers Chase Ryan and Keith Ellison have c...,1
3,the millionaire next door: the surprising secr...,NaN,"Thomas J. Stanley, William D. Danko",72168,3217,4.04,27594,25219,14855,3414,1086,258.0,Gallery Books,"Economics-Finance 1162, Nonfiction 910, Busine...",Independent Publisher Book Award (IPPY) Nomine...,The incredible national bestseller that is cha...,0
4,black sheep,NaN,Georgette Heyer,9538,775,4.05,3298,3831,2042,304,63,252.0,Arrow,"Romance 550, Historical-Historical Fiction 316...",NaN,With her high-spirited intelligence and good l...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44360,beauty awakened,(Angels of the Dark #2),Gena Showalter,11894,793,4.15,5227,4031,2032,453,151,447.0,HQN Books,"Romance-Paranormal Romance 405, Fantasy-Parano...",NaN,"His name is Koldo. He is scarred, powerful, hi...",1
44362,the stranger i married,NaN,Sylvia Day,13295,805,3.87,4220,4733,3116,848,378,312.0,Kensington Trade,"Romance-Historical Romance 335, Romance 312, H...",NaN,"The unabridged, downloadable audiobook edition...",0
44363,the opposite of loneliness: essays and stories,NaN,Marina Keegan,42609,4282,3.84,12461,15191,11202,3011,744,208.0,Scribner,"Nonfiction 1307, Short Stories 766, Writing-Es...","Goodreads Choice Award for Nonfiction (2014), ...",An affecting and hope-filled posthumous collec...,0
44364,sadako will leben,NaN,Karl Bruckner,1583,64,4.17,673,592,251,51,16,264.0,Arena,"Fiction 13, Childrens 11, Historical-Historica...","Austrian National Prize (1961), City of Vienna...","6. August 1945, 8 Uhr 15 Minuten - die kleine ...",0
44366,going rogue: an american life,NaN,"Sarah Palin, Lynn Vincent, Dewey Whetsell",11359,1246,3.28,2379,3085,2921,1262,1712,413.0,Harper,"Biography 176, Nonfiction 171, Politics 165, B...",NaN,is the #1 bestselling memoir from Sarah Palin...,0

In [20]:
good_reads.isnull().sum().sort_values(ascending=False)

awards                32664
series                23047
nyt_best_seller           0
four_star_ratings         0
author                    0
rating_count              0
review_count              0
average_rating            0
five_star_ratings         0
three_star_ratings        0
description               0
two_star_ratings          0
one_star_ratings          0
number_of_pages           0
publisher                 0
genre_and_votes           0
title                     0
dtype: int64

In [21]:
pd.to_pickle(good_reads, 'data.pkl')

In [243]:
pd.to_pickle(good_reads, 'clean_data.pkl')

In [244]:
good_reads.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42340 entries, 0 to 44366
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               42340 non-null  object
 1   author              42340 non-null  object
 2   rating_count        42340 non-null  int64
 3   review_count        42340 non-null  int64
 4   average_rating      42340 non-null  float64
 5   five_star_ratings   42340 non-null  int64
 6   four_star_ratings   42340 non-null  int64
 7   three_star_ratings  42340 non-null  int64
 8   two_star_ratings    42340 non-null  int64
 9   one_star_ratings    42340 non-null  int64
 10  number_of_pages     42340 non-null  float64
 11  publisher           42340 non-null  object
 12  genre_and_votes     42340 non-null  object
 13  description         42340 non-null  object
 14  is_series           42340 non-null  int64
 15  has_won_award       42340 non-null  int64
 16  nyt_best_seller     42340 non-null  int64
dtypes: float64(2), int64(10), object(5)
memory usage: 7.1+ MB

In [22]:
import pandas as pd
pd.read_pickle('data.pkl')

,title,series,author,rating_count,review_count,average_rating,five_star_ratings,four_star_ratings,three_star_ratings,two_star_ratings,one_star_ratings,number_of_pages,publisher,genre_and_votes,awards,description,nyt_best_seller
0,inner circle,(Private #5),"Kate Brian, Julian Peploe",7597,196,4.03,3045,2323,1748,389,92,220.0,Simon Schuster Books for Young Readers,"Young Adult 161, Mystery 45, Romance 32",NaN,Reed Brennan arrived at Easton Academy expecti...,0
1,a time to embrace,(Timeless Love #2),Karen Kingsbury,4179,177,4.35,2255,1290,518,93,23,400.0,Thomas Nelson,"Christian Fiction 114, Christian 45, Fiction 3...",NaN,"Ideje az Ã¶lelÃ©snek TÃ¶rtÃ©net a remÃ©nyrÅl,...",0
2,take two,(Above the Line #2),Karen Kingsbury,6288,218,4.23,3000,2020,1041,183,44,320.0,Zondervan,"Christian Fiction 174, Christian 81, Fiction 58",NaN,Filmmakers Chase Ryan and Keith Ellison have c...,1
3,the millionaire next door: the surprising secr...,NaN,"Thomas J. Stanley, William D. Danko",72168,3217,4.04,27594,25219,14855,3414,1086,258.0,Gallery Books,"Economics-Finance 1162, Nonfiction 910, Busine...",Independent Publisher Book Award (IPPY) Nomine...,The incredible national bestseller that is cha...,0
4,black sheep,NaN,Georgette Heyer,9538,775,4.05,3298,3831,2042,304,63,252.0,Arrow,"Romance 550, Historical-Historical Fiction 316...",NaN,With her high-spirited intelligence and good l...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44360,beauty awakened,(Angels of the Dark #2),Gena Showalter,11894,793,4.15,5227,4031,2032,453,151,447.0,HQN Books,"Romance-Paranormal Romance 405, Fantasy-Parano...",NaN,"His name is Koldo. He is scarred, powerful, hi...",1
44362,the stranger i married,NaN,Sylvia Day,13295,805,3.87,4220,4733,3116,848,378,312.0,Kensington Trade,"Romance-Historical Romance 335, Romance 312, H...",NaN,"The unabridged, downloadable audiobook edition...",0
44363,the opposite of loneliness: essays and stories,NaN,Marina Keegan,42609,4282,3.84,12461,15191,11202,3011,744,208.0,Scribner,"Nonfiction 1307, Short Stories 766, Writing-Es...","Goodreads Choice Award for Nonfiction (2014), ...",An affecting and hope-filled posthumous collec...,0
44364,sadako will leben,NaN,Karl Bruckner,1583,64,4.17,673,592,251,51,16,264.0,Arena,"Fiction 13, Childrens 11, Historical-Historica...","Austrian National Prize (1961), City of Vienna...","6. August 1945, 8 Uhr 15 Minuten - die kleine ...",0
44366,going rogue: an american life,NaN,"Sarah Palin, Lynn Vincent, Dewey Whetsell",11359,1246,3.28,2379,3085,2921,1262,1712,413.0,Harper,"Biography 176, Nonfiction 171, Politics 165, B...",NaN,is the #1 bestselling memoir from Sarah Palin...,0

In [25]:
good_reads.to_csv('data.csv')

In [26]:
good_reads.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42340 entries, 0 to 44366
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               42340 non-null  object
 1   series              19293 non-null  object
 2   author              42340 non-null  object
 3   rating_count        42340 non-null  int64
 4   review_count        42340 non-null  int64
 5   average_rating      42340 non-null  float64
 6   five_star_ratings   42340 non-null  int64
 7   four_star_ratings   42340 non-null  int64
 8   three_star_ratings  42340 non-null  int64
 9   two_star_ratings    42340 non-null  int64
 10  one_star_ratings    42340 non-null  int64
 11  number_of_pages     42340 non-null  float64
 12  publisher           42340 non-null  object
 13  genre_and_votes     42340 non-null  object
 14  awards              9676 non-null   object
 15  description         42340 non-null  object
 16  nyt_best_seller     42340 non-null  int64
dtypes: float64(2), int64(8), object(7)
memory usage: 5.8+ MB